/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for typescript to be aware of RPCs and their return types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type GreetUserInput = { name: string; loud: boolean; }
export type GreetUserOutput = { message: string; timestamp: string; }
export type AddNumbersInput = { a: number; b: number; }
export type AddNumbersOutput = { operation: string; operands: number[]; result: number; expression: string; }
export type SubtractNumbersInput = { a: number; b: number; }
export type SubtractNumbersOutput = { operation: string; operands: number[]; result: number; expression: string; }
export type MultiplyNumbersInput = { a: number; b: number; }
export type MultiplyNumbersOutput = { operation: string; operands: number[]; result: number; expression: string; }
export type DivideNumbersInput = { a: number; b: number; }
export type DivideNumbersOutput = { operation: string; operands: number[]; result: number; expression: string; }
export type CreateUserInput = { username: string; email: string; admin?: boolean; }
export type CreateUserOutput = { id: number; username: string; email: string; admin: boolean; created: string; }
export type ListUsersInput = { limit?: number; admin?: boolean; }
export type ListUsersOutput = { users: any[]; total: number; filtered: boolean; }
export type ProcessFileInput = { path: string; action: "read" | "info" | "delete"; backup?: boolean; }
export type ProcessFileOutput = { path: string; action: string; backup: boolean; processed: boolean; timestamp: string; size: number; }

interface RPCHandler<I, O> {
    input: I;
    output: O;
}

export type RPCMap = {
};


export type RPCInvoke = <Name extends keyof RPCMap>(
  name: Name,
  data: RPCMap[Name]['input'],
  options?: {
    location?: 'local' | 'remote' | 'auto'
  }
) => Promise<RPCMap[Name]['output']>

// Import WorkflowMap for workflow typing
import type { WorkflowMap } from '../workflow/pikku-workflow-map.gen.js'

export type TypedPikkuRPC = {
  depth: number;
  global: boolean;
  invoke: RPCInvoke;
  invokeExposed: (name: string, data: any) => Promise<any>;
  startWorkflow: <Name extends keyof WorkflowMap>(
    name: Name,
    input: WorkflowMap[Name]['input']
  ) => Promise<{ runId: string }>;
}
  