/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "greetUser": {
    "pikkuFuncName": "greetUser",
    "name": "greetUser",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "GreetUserInput",
    "outputSchemaName": "GreetUserOutput",
    "inputs": [
      "GreetUserInput"
    ],
    "outputs": [
      "GreetUserOutput"
    ],
    "isDirectFunction": false
  },
  "addNumbers": {
    "pikkuFuncName": "addNumbers",
    "name": "addNumbers",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "AddNumbersInput",
    "outputSchemaName": "AddNumbersOutput",
    "inputs": [
      "AddNumbersInput"
    ],
    "outputs": [
      "AddNumbersOutput"
    ],
    "isDirectFunction": false
  },
  "subtractNumbers": {
    "pikkuFuncName": "subtractNumbers",
    "name": "subtractNumbers",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "SubtractNumbersInput",
    "outputSchemaName": "SubtractNumbersOutput",
    "inputs": [
      "SubtractNumbersInput"
    ],
    "outputs": [
      "SubtractNumbersOutput"
    ],
    "isDirectFunction": false
  },
  "multiplyNumbers": {
    "pikkuFuncName": "multiplyNumbers",
    "name": "multiplyNumbers",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "MultiplyNumbersInput",
    "outputSchemaName": "MultiplyNumbersOutput",
    "inputs": [
      "MultiplyNumbersInput"
    ],
    "outputs": [
      "MultiplyNumbersOutput"
    ],
    "isDirectFunction": false
  },
  "divideNumbers": {
    "pikkuFuncName": "divideNumbers",
    "name": "divideNumbers",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "DivideNumbersInput",
    "outputSchemaName": "DivideNumbersOutput",
    "inputs": [
      "DivideNumbersInput"
    ],
    "outputs": [
      "DivideNumbersOutput"
    ],
    "isDirectFunction": false
  },
  "createUser": {
    "pikkuFuncName": "createUser",
    "name": "createUser",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "CreateUserInput",
    "outputSchemaName": "CreateUserOutput",
    "inputs": [
      "CreateUserInput"
    ],
    "outputs": [
      "CreateUserOutput"
    ],
    "isDirectFunction": false
  },
  "listUsers": {
    "pikkuFuncName": "listUsers",
    "name": "listUsers",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "ListUsersInput",
    "outputSchemaName": "ListUsersOutput",
    "inputs": [
      "ListUsersInput"
    ],
    "outputs": [
      "ListUsersOutput"
    ],
    "isDirectFunction": false
  },
  "processFile": {
    "pikkuFuncName": "processFile",
    "name": "processFile",
    "services": {
      "optimized": false,
      "services": []
    },
    "inputSchemaName": "ProcessFileInput",
    "outputSchemaName": "ProcessFileOutput",
    "inputs": [
      "ProcessFileInput"
    ],
    "outputs": [
      "ProcessFileOutput"
    ],
    "isDirectFunction": false
  }
})